### PR TITLE
feature/reviews

### PR DESCRIPTION
**Pull request by josantana**
#### What is the purpose of this pull request?

Adds a new query to retrieve product reviews. The previous routes were oddly named "review" and "reviews", despite of their response: just ratings. That doesn't make sense anymore. That's why I've renamed them to "rating" and "ratings", using the "reviews" query for the new one. Besides the naming, there is no change to its behaviour. But it should be published as a major change to avoid breaking the app on stores where it is already installed.

#### What problem is this solving?

The previous version delivered only the rating, which is OK for product shelfs and to render the product score on its respective page, for SEO purposes. But there is a lack of other YourViews features like reviews, Q&A and so on. This PR is the first move to accomplish that. If it got approved, I intent to send new PRs (minors, this time) resolving the remaining features.

#### How should this be manually tested?

There's no test tool available on this repository, so I've tested with the queries below on my account.

[yourviews-graphql-PR#2.txt](https://github.com/vtex-apps/yourviews-graphql/files/4188033/yourviews-graphql-PR.2.txt)

#### Types of changes

* [ ] Bug fix (a non-breaking change which fixes an issue)
* [ ] New feature (a non-breaking change which adds functionality)
* [x] Breaking change (fix or feature that would cause existing functionality to change)
* [ ] Requires change to documentation, which has been updated accordingly.

### CODE REVIEW

**Review by klzns — CHANGES_REQUESTED** [review]
Do you mind allowing us to push to your branch?

https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork

There are some things that we could fix.

**Comment by josantana** [comment]
Sure thing, @klzns - but I could not find the option you mentioned (as seen below).

Screen Shot 2020-02-12 at 13 43 45

**Comment by klzns** [comment]
🤔 weird

Can you copy those 2 commits, please?

https://github.com/vtex-apps/yourviews-graphql/commits/feature/reviews-vtex

It's important that those changes are documented.

**Review by klzns — APPROVED** [review]

**Comment by klzns** [comment]
@allcontributors add @josantana for code

**Pull request merged**
